### ISSUE TITLE
Incorrectly identifying desktops in manual pool plugin

### ISSUE THREAD

**Issue by zenmatrix** [vCheckReport/vCheck-HorizonView#16]
I just tested the new code for 14 Manual Desktop Pool Information and the query is getting desktops that are not part of that pool. Here is the output of the plugin if I look at manualpoolstatus in ise

Name              : Pool1
Available         : 64
Connected         : 18
Disconnected      : 49
Already_Used      : 0
Agent_Unreachable : 0
Error             : 0

Name              : Pool2
Available         : 64
Connected         : 18
Disconnected      : 49
Already_Used      : 0
Agent_Unreachable : 0
Error             : 0

There are exactly the same and if I look in horizon they are different. When I look at the $desktops variable from the last pool it looked at I see desktops that aren't part of that pool. Let me know if I can help.

**Comment by Magneet** [comment]
Found the cause: the filter definition wasn't applied to the query definition and it was for none of the pool informations. I fixed this in my own repo at https://github.com/Magneet/vCheck-HorizonView/tree/master/Plugins/20%20Desktop can you test it with those scripts? If it works properly by then I will add it to the current pull request

**Comment by zenmatrix** [comment]
I just tried, its gave me an error saying $def wasn't defined, so I tried $defn and then that worked but got no results. I also tried changing $pool.base.name to $($pool.base.name) and that didn't make a difference.

**Comment by zenmatrix** [comment]
I think the filter is wrong but I can't get it to work. It should be something like

$defn.filter = New-Object VMware.Hv.QueryFilterEquals -Property @{ 'memberName' = 'base.desktop.id'; 'value' = "$pool.id" }

I think but I get invalid types when I try. I was able to get it to work as expected by letting the filter not apply and looping through the desktops and filtering it out like this

$filteredDesktops=@()

foreach($desktop in $desktops)

{

$desktopPoolId=$desktop.Base.Desktop.Id.ToString()

$poolId=$pool.id.Id.ToString()

if($desktopPoolId -eq $poolId)

{

$filteredDesktops+=$desktop

}

}

$desktops=$filteredDesktops


I just can't seem to get the query service to work right.

**Comment by Magneet** [comment]
what Horizon version are you at?

**Comment by Magneet** [comment]
And when filtering on id you need to do this:
`$defn.filter=New-Object VMware.Hv.QueryFilterEquals -property @{'memberName'='base.desktop'; 'value'=$pool.id}
can you test that ( I ended up using that to get id's for a recompose in my latest blogpost so must have had issues at some point with doing it on the name)?

**Comment by zenmatrix** [comment]
I'm using 7.4. Yep can't believe I missed that part, taking the quotes off of $pool.id worked. Thank you we are a big fan of the regular vcheck so we are excited to get this working.

**Comment by Magneet** [comment]
nice, I added it in the current open pull request https://github.com/vCheckReport/vCheck-HorizonView/pull/15

**Comment by Magneet** [comment]
this issue is solved and can be closed
