### ISSUE TITLE
Add info to: 15 Instant Clone Desktop Pool Information

### ISSUE THREAD

**Issue by amikkelsendk** [vCheckReport/vCheck-HorizonView#19]
Hi,
in the plugin "15 Instant Clone Desktop Pool Information"
After the line:
"Name" = $Poolname;
Please add the following line:
"Display_Name" = $pool.base.DisplayName;

and change the line
$automatedpoolstatus | select Name,Pool_Image,Pool_Snapshot,Desktop_Count,Available,Connected,Disconnected,Maintenance,Provisioning,Customizing,Already_Used,Agent_Unreachable,Error,Deleting,Provisioning_Error
to:
$automatedpoolstatus | select Name,Display_Name,Pool_Image,Pool_Snapshot,Desktop_Count,Available,Connected,Disconnected,Maintenance,Provisioning,Customizing,Already_Used,Agent_Unreachable,Error,Deleting,Provisioning_Error

Thanks in advance 

A. Mikkelsen

**Comment by Magneet** [comment]
The pool name should be enough, this will add too much for an overview that's already very full.

**Comment by Magneet** [comment]
not going to implement this as it's already to busy in this table
