### ISSUE TITLE
RDS Farm Health plugin issue

### ISSUE THREAD

**Issue by Ankojin** [vCheckReport/vCheck-HorizonView#26]
Hi Wouter Kursten,

Missing App Column details showing  for all  RDS Farm instead of Missing farm.
Could you please help on this ?

![image](https://user-images.githubusercontent.com/42596984/94664639-b5a04500-033d-11eb-8d1f-6cf5effca487.png)

Thansk,
Ankoji

**Comment by Magneet** [comment]
@Ankojin found the culprit can you check the vsersion on my repo before I put it here? https://github.com/Magneet/vCheck-HorizonView

**Comment by Ankojin** [comment]
> @Ankojin found the culprit can you check the vsersion on my repo before I put it here? https://github.com/Magneet/vCheck-HorizonView

Hi ,

There is typo at @missingapps=$null , I have corrected to $missingapps=$null. 
Now  RDS Farm Health Pulgin is working fine.

![image](https://user-images.githubusercontent.com/42596984/94677387-619e5c00-034f-11eb-9d98-f963439e0f66.png)

Thanks for your quick support .

Thanks,
Ankoji

**Comment by Magneet** [comment]
fixed and thank you for reporting this!
